
package hbi.core.customer.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerWeb", targetNamespace = "http://service.customer.core.hbi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerWeb {


    /**
     * 
     * @param result
     * @return
     *     returns hbi.core.customer.ws.CustomerWebservice
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCustomerBack", targetNamespace = "http://service.customer.core.hbi/", className = "hbi.core.customer.ws.GetCustomerBack")
    @ResponseWrapper(localName = "getCustomerBackResponse", targetNamespace = "http://service.customer.core.hbi/", className = "hbi.core.customer.ws.GetCustomerBackResponse")
    public CustomerWebservice getCustomerBack(
        @WebParam(name = "result", targetNamespace = "")
        CustomerVo result);

}
