
package hbi.core.customer.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "customerWeb", targetNamespace = "http://impl.service.customer.core.hbi/", wsdlLocation = "http://localhost:8080/ws/CustomerWeb?wsdl")
public class CustomerWeb_Service
    extends Service
{

    private final static URL CUSTOMERWEB_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERWEB_EXCEPTION;
    private final static QName CUSTOMERWEB_QNAME = new QName("http://impl.service.customer.core.hbi/", "customerWeb");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/CustomerWeb?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERWEB_WSDL_LOCATION = url;
        CUSTOMERWEB_EXCEPTION = e;
    }

    public CustomerWeb_Service() {
        super(__getWsdlLocation(), CUSTOMERWEB_QNAME);
    }

    public CustomerWeb_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERWEB_QNAME, features);
    }

    public CustomerWeb_Service(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERWEB_QNAME);
    }

    public CustomerWeb_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERWEB_QNAME, features);
    }

    public CustomerWeb_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerWeb_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerWeb
     */
    @WebEndpoint(name = "CustomerWebImplPort")
    public CustomerWeb getCustomerWebImplPort() {
        return super.getPort(new QName("http://impl.service.customer.core.hbi/", "CustomerWebImplPort"), CustomerWeb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerWeb
     */
    @WebEndpoint(name = "CustomerWebImplPort")
    public CustomerWeb getCustomerWebImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.customer.core.hbi/", "CustomerWebImplPort"), CustomerWeb.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERWEB_EXCEPTION!= null) {
            throw CUSTOMERWEB_EXCEPTION;
        }
        return CUSTOMERWEB_WSDL_LOCATION;
    }

}
