package hbi.core.customer.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "rent_customer")
public class Customer extends BaseDTO {

     public static final String FIELD_ID = "id";
     public static final String FIELD_CUSTOMER_NAME = "customerName";
     public static final String FIELD_CUSTOMER_TITLE = "customerTitle";
     public static final String FIELD_CERTIFICATE_TYPE = "certificateType";
     public static final String FIELD_CERTIFICATE_CODE = "certificateCode";
     public static final String FIELD_GENDER = "gender";
     public static final String FIELD_PHONE = "phone";


     @Id
     @GeneratedValue
     private Long id;

     @Length(max = 100)
     private String customerName;

     @Length(max = 50)
     private String customerTitle;

     @Length(max = 50)
     private String certificateType;

     private Long certificateCode;

     @Length(max = 20)
     private String gender;

     private Long phone;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setCustomerName(String customerName){
         this.customerName = customerName;
     }

     public String getCustomerName(){
         return customerName;
     }

     public void setCustomerTitle(String customerTitle){
         this.customerTitle = customerTitle;
     }

     public String getCustomerTitle(){
         return customerTitle;
     }

     public void setCertificateType(String certificateType){
         this.certificateType = certificateType;
     }

     public String getCertificateType(){
         return certificateType;
     }

     public void setCertificateCode(Long certificateCode){
         this.certificateCode = certificateCode;
     }

     public Long getCertificateCode(){
         return certificateCode;
     }

     public void setGender(String gender){
         this.gender = gender;
     }

     public String getGender(){
         return gender;
     }

     public void setPhone(Long phone){
         this.phone = phone;
     }

     public Long getPhone(){
         return phone;
     }

     }
