package hbi.core.activity.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;

import java.io.Serializable;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.format.annotation.DateTimeFormat;

@ExtensionAttribute(disable=true)
@Table(name = "rent_activity_demo1")
public class ActivityDemo1 extends BaseDTO implements Serializable {

     public static final String FIELD_ID = "id";
     public static final String FIELD_ACTIVITY_NAME = "activityName";
     public static final String FIELD_ACTIVITY_DATA = "activityData";
     public static final String FIELD_NAME = "name";
     public static final String FIELD_ACTIVITY_START_DATA = "activityStartData";
     public static final String FIELD_ACTIVITY_STOP_DATA = "activityStopData";
     public static final String FIELD_ACTIVITY_SATAUS = "activitySataus";
     public static final String FIELD_ACTIVITY_TEXT = "activityText";
     public static final String FIELD_USER_ROLE = "userRole";
     public static final String FIELD_ACTIVITY_EMPLOYEE = "activityEmployee";
     public static final String FIELD_ACTIVITE_MONEY = "activiteMoney";



    @Id
     @GeneratedValue
     private Long id; //活动id

     //@NotEmpty
     @Length(max = 50)
     private String activityName; //活动名称


    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date activityData; //活动创建日期

     //@NotEmpty
     @Length(max = 100)
     private String name; //创建人


    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date activityStartData; //发布日期


    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date activityStopData; //结束日期

     //@NotEmpty
     @Length(max = 50)
     private String activitySataus; //状态

     //@NotEmpty
     @Length(max = 100)
     private String activityText; //活动内容

     @Length(max = 50)
     private String userRole; //角色

     //@NotEmpty
     @Length(max = 50)
     private String activityEmployee; //负责管理员工

     private Double activiteMoney; //活动金额


    public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setActivityName(String activityName){
         this.activityName = activityName;
     }

     public String getActivityName(){
         return activityName;
     }

     public void setActivityData(Date activityData){
         this.activityData = activityData;
     }

     public Date getActivityData(){
         return activityData;
     }

     public void setName(String name){
         this.name = name;
     }

     public String getName(){
         return name;
     }

     public void setActivityStartData(Date activityStartData){
         this.activityStartData = activityStartData;
     }

     public Date getActivityStartData(){
         return activityStartData;
     }

     public void setActivityStopData(Date activityStopData){
         this.activityStopData = activityStopData;
     }

     public Date getActivityStopData(){
         return activityStopData;
     }

     public void setActivitySataus(String activitySataus){
         this.activitySataus = activitySataus;
     }

     public String getActivitySataus(){
         return activitySataus;
     }

     public void setActivityText(String activityText){
         this.activityText = activityText;
     }

     public String getActivityText(){
         return activityText;
     }

     public void setUserRole(String userRole){
         this.userRole = userRole;
     }

     public String getUserRole(){
         return userRole;
     }

     public void setActivityEmployee(String activityEmployee){
         this.activityEmployee = activityEmployee;
     }

     public String getActivityEmployee(){
         return activityEmployee;
     }

     public void setActiviteMoney(Double activiteMoney){
         this.activiteMoney = activiteMoney;
     }

     public Double getActiviteMoney(){
         return activiteMoney;
     }

     }
